site_name: Meter Plugin SDK for C

theme: readthedocs

pages:
- Home: index.md
- Installation: 'install/index.md'
- Using: 'using/index.md'
- Examples:
    - Hello: 'examples/hello.md' 
    - Random: 'examples/random.md'
    - UDP: 'examples/udp.md'
