site_name: Meter Plugin SDK for C

theme: readthedocs

pages:
- Home: index.md
- Installation: 'install/index.md'
- Tutorial: 'tutorial/index.md'
- Development: 'development/index.md'
- Examples:
    - Hello: 'examples/hello.md' 
    - Random: 'examples/random.md'
    - UDP: 'examples/udp.md'
    - Raspberry Pi: 'examples/raspberry_pi.md'
- Deploy Meter to Raspberry Pi: 'tutorial/install_meter.md'
