site_name: Meter Plugin SDK for C

theme: readthedocs

pages:
- Home: index.md
- Installation: 'install/index.md'
- Tutorial: 'tutorial/index.md'
- Development: 'development/index.md'
- Examples: 'examples/index.md'
- Deploy Meter to Raspberry Pi: 'tutorial/install_meter.md'
